{
 "title": "Validator Uptime",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Validator",
    "query": {
     "query": "label_values({validator=\"$Validator\"},validator)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{validator=\"$Validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "uptime{validator=\"$Validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state{validator=\"$Validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consecutive Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "consecutive_missed_blocks{validator=\"$Validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State History",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "state{validator=\"$Validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "update_success", "legendFormat": "__auto" }
   ]
  }
 ]
}